
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculadoraWSPService", targetNamespace = "http://server/", wsdlLocation = "http://192.168.1.65:8080/ServerOperaciones/CalculadoraWSPService?wsdl")
public class CalculadoraWSPService
    extends Service
{

    private final static URL CALCULADORAWSPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULADORAWSPSERVICE_EXCEPTION;
    private final static QName CALCULADORAWSPSERVICE_QNAME = new QName("http://server/", "CalculadoraWSPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.65:8080/ServerOperaciones/CalculadoraWSPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULADORAWSPSERVICE_WSDL_LOCATION = url;
        CALCULADORAWSPSERVICE_EXCEPTION = e;
    }

    public CalculadoraWSPService() {
        super(__getWsdlLocation(), CALCULADORAWSPSERVICE_QNAME);
    }

    public CalculadoraWSPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULADORAWSPSERVICE_QNAME, features);
    }

    public CalculadoraWSPService(URL wsdlLocation) {
        super(wsdlLocation, CALCULADORAWSPSERVICE_QNAME);
    }

    public CalculadoraWSPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULADORAWSPSERVICE_QNAME, features);
    }

    public CalculadoraWSPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraWSPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculadoraWSP
     */
    @WebEndpoint(name = "CalculadoraWSPPort")
    public CalculadoraWSP getCalculadoraWSPPort() {
        return super.getPort(new QName("http://server/", "CalculadoraWSPPort"), CalculadoraWSP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadoraWSP
     */
    @WebEndpoint(name = "CalculadoraWSPPort")
    public CalculadoraWSP getCalculadoraWSPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "CalculadoraWSPPort"), CalculadoraWSP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULADORAWSPSERVICE_EXCEPTION!= null) {
            throw CALCULADORAWSPSERVICE_EXCEPTION;
        }
        return CALCULADORAWSPSERVICE_WSDL_LOCATION;
    }

}
