
package server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadoraWSP", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadoraWSP {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContadorPeticiones", targetNamespace = "http://server/", className = "server.GetContadorPeticiones")
    @ResponseWrapper(localName = "getContadorPeticionesResponse", targetNamespace = "http://server/", className = "server.GetContadorPeticionesResponse")
    @Action(input = "http://server/CalculadoraWSP/getContadorPeticionesRequest", output = "http://server/CalculadoraWSP/getContadorPeticionesResponse")
    public int getContadorPeticiones();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "restar", targetNamespace = "http://server/", className = "server.Restar")
    @ResponseWrapper(localName = "restarResponse", targetNamespace = "http://server/", className = "server.RestarResponse")
    @Action(input = "http://server/CalculadoraWSP/restarRequest", output = "http://server/CalculadoraWSP/restarResponse")
    public int restar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dividir", targetNamespace = "http://server/", className = "server.Dividir")
    @ResponseWrapper(localName = "dividirResponse", targetNamespace = "http://server/", className = "server.DividirResponse")
    @Action(input = "http://server/CalculadoraWSP/dividirRequest", output = "http://server/CalculadoraWSP/dividirResponse")
    public int dividir(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sumar", targetNamespace = "http://server/", className = "server.Sumar")
    @ResponseWrapper(localName = "sumarResponse", targetNamespace = "http://server/", className = "server.SumarResponse")
    @Action(input = "http://server/CalculadoraWSP/sumarRequest", output = "http://server/CalculadoraWSP/sumarResponse")
    public int sumar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplicar", targetNamespace = "http://server/", className = "server.Multiplicar")
    @ResponseWrapper(localName = "multiplicarResponse", targetNamespace = "http://server/", className = "server.MultiplicarResponse")
    @Action(input = "http://server/CalculadoraWSP/multiplicarRequest", output = "http://server/CalculadoraWSP/multiplicarResponse")
    public int multiplicar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
